Repository 0xPolygon/cdk, pull requests merged in 2025-01, with the labels that each got.

#262 feat: more logs for `l1infotreesyncer`
  .github/workflows/test-e2e.yml
  bridgesync/e2e_test.go
  cmd/run.go
  crates/cdk/build.rs
  l1infotreesync/e2e_test.go
  l1infotreesync/migrations/l1infotreesync0003.sql
  l1infotreesync/migrations/migrations.go
  l1infotreesync/processor.go
  reorgdetector/reorgdetector.go
  reorgdetector/reorgdetector_db.go
  reorgdetector/reorgdetector_sub.go
  reorgdetector/reorgdetector_test.go
  sync/driver.go
  sync/evmdownloader.go
  sync/evmdriver.go
  sync/evmdriver_test.go
  test/aggoraclehelpers/aggoracle_e2e.go
Labels: l1infotreesync

#267 fix: multi chains pessimistic proofs e2e tests
  .github/workflows/test-e2e-multi_pp.yml
  .github/workflows/test-e2e.yml
  test/combinations/fork12-pessimistic-multi-attach-second-cdk.yml
  test/combinations/fork12-pessimistic-multi.yml
  test/combinations/fork12-pessimistic.yml
Labels: ci

#266 fix: `reorg detector` removes `finalized` block
  reorgdetector/reorgdetector.go
  reorgdetector/reorgdetector_db.go
  reorgdetector/reorgdetector_test.go
Labels: bug

#270 fix: seq-sender latestVirtualTime
  sequencesender/ethtx.go
  sequencesender/ethtx_test.go
  sequencesender/sequencesender.go
Labels: seqsender

#276 feat: cherrypick issue fixes #270 and #254
  go.mod
  go.sum
  sequencesender/ethtx.go
  sequencesender/ethtx_test.go
  sequencesender/sequencesender.go
Labels: seqsender

#277 fix: cherry-pick case of eth_getBlockByHash response null or tstamp zero (#275)
  rpc/batch.go
  rpc/batch_test.go
Labels: seqsender, cherry-pick

#272 fix: `reorg detector` and `syncer` issues on `develop`
  bridgesync/bridgesync.go
  bridgesync/bridgesync_test.go
  bridgesync/e2e_test.go
  cmd/run.go
  etherman/types.go
  l1infotreesync/e2e_test.go
  l1infotreesync/l1infotreesync.go
  l1infotreesync/processor.go
  sync/evmdownloader.go
  sync/evmdownloader_test.go
  sync/evmdriver.go
  sync/evmtypes.go
  sync/mock_downloader_test.go
  test/helpers/e2e.go
  test/helpers/wait.go
Labels: l1infotreesync

#283 feat: more logs for `l1infotreesyncer` `cherry-pick`
  cmd/run.go
  l1infotreesync/e2e_test.go
  l1infotreesync/migrations/l1infotreesync0003.sql
  l1infotreesync/migrations/migrations.go
  l1infotreesync/processor.go
  reorgdetector/reorgdetector.go
  reorgdetector/reorgdetector_db.go
  reorgdetector/reorgdetector_sub.go
  reorgdetector/reorgdetector_test.go
  sync/driver.go
  sync/evmdownloader.go
  sync/evmdriver.go
  sync/evmdriver_test.go
  test/helpers/e2e.go
Labels: cherry-pick

#265 fix: chainID in aggOracle configs
  aggoracle/chaingersender/evm.go
  cmd/run.go
  config/default.go
  go.mod
  go.sum
Labels: aggoracle

#285 fix: hash meddler error
  db/meddler_test.go
  go.mod
  go.sum
Labels: aggsender

#288 fix: hash meddler error `cherry-pick` `0.5.1`
  db/meddler_test.go
  go.mod
  go.sum
Labels: cherry-pick

#289 fix: syncer spamming RPC and reaching tip of chain
  sync/evmdownloader.go
  sync/evmdownloader_test.go
Labels: l1infotreesync
